#pragma config(Sensor, dgtl2,  solenoid2,      sensorDigitalOut)
#pragma config(Motor,  port2,           Dropper,       tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string color = "";
void detectColor(){
  	// here the color detection
  	color = "Yellow";
  }
task main()
{
  /*while(true)                     // Loop Forever
  {
    if(vexRT[Btn6U] == 1)         // If button 6U (upper right shoulder button) is pressed:
    {
      SensorValue[solenoid1] = 1;  // ...activate the solenoid.
    }
    else                          // If button 6U (upper right shoulder button) is  NOT pressed:
    {
      SensorValue[solenoid1] = 0;  // ..deactivate the solenoid.
    }
  }*/
 while(true){
  SensorValue[solenoid2] = 0;
  SensorValue[solenoid2] = 1;
}

  /*while(true){
  	// Drops 1 m&m
  	motor[Dropper] = 30;
  	Sleep(30);// rotate to drop 1 m&m
  	motor[Dropper] = 0;

  	detectColor();

  	Sleep(50);// wait for the m&m to drop

  	if(color == "Yellow"){
  		// push the upper piston out
  			SensorValue[solenoid2] = 1;
  			Sleep(15);
				SensorValue[solenoid2] = 0;
  	}


  }*/
}
